name: Tests

concurrency:
  cancel-in-progress: true
  group: ${{github.workflow}}-${{github.ref}}

on:
  push:
    branches: [main, "release/**"]
  pull_request:
    branches: [main, "release/**"]

jobs:
  tests:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        rust: [stable, "1.66"] # MSRV
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Install toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.rust }}
          targets: riscv32imac-unknown-none-elf

      - uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: true

      - name: cargo build
        run: cargo build --workspace

      - name: cargo build no_std
        run: cargo build --workspace --target riscv32imac-unknown-none-elf --no-default-features

      - name: cargo test
        if: ${{ matrix.rust == 'stable' }}
        run: cargo test --workspace

      - name: cargo test all features
        if: ${{ matrix.rust == 'stable' }}
        run: cargo test --workspace --all-features

  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Install toolchain
        uses: dtolnay/rust-toolchain@nightly
        with:
          components: rustfmt, clippy

      - uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: true

      - name: cargo fmt
        run: cargo +nightly fmt --all -- --check

      - name: cargo clippy
        run: cargo +nightly clippy --workspace --all-features -- -D warnings

      - name: cargo check no-default-features
        run: |
          cd crates/revm
          cargo check --no-default-features
      - name: cargo check serde
        run: |
          cd crates/revm
          cargo check --no-default-features --features serde
      - name: cargo check std
        run: |
          cd crates/revm
          cargo check --no-default-features --features std
